version: '3'

networks:
  terracotta-net:
# following line to uncomment when using a "real" Docker swarm, not Docker Swarm mode
    driver: overlay

services:
  client:
#    build: sample-ehcache-client/
    image: sample-ehcache-client:5.2.0
    environment:
     - TERRACOTTA_SERVER_URL=terracotta-1:9510,terracotta-2:9510
    networks:
     - terracotta-net

  terracotta-1:
    hostname: terracotta-1
#    build: server/
    image: terracotta-server-oss:5.2.0
    environment:
     - TC_SERVER1=terracotta-1
     - TC_SERVER2=terracotta-2
    networks:
     - terracotta-net

  terracotta-2:
    hostname: terracotta-2
#    build: server/
    image: terracotta-server-oss:5.2.0
    environment:
     - TC_SERVER1=terracotta-1
     - TC_SERVER2=terracotta-2
    networks:
     - terracotta-net